"""Draws the isometric warehouse for the map home.

A copy of the design's iso.py with the vehicles split out, so the trucks and
forklifts can move on their own layers. Run from apps/desktop:

    python3 scripts/warehouse_layers.py

It writes src/ui/map/warehouseLayers.ts. Nothing in it is user data.
"""
def f(n): return ('%.1f'%n).rstrip('0').rstrip('.')
def TOP(z): return f'matrix(.866 .5 -.866 .5 0 {f(-z)})'
def LEFT(y1): return f'matrix(.866 .5 0 1 {f(-.866*y1)} {f(.5*y1)})'
def RIGHT(x1): return f'matrix(-.866 .5 0 1 {f(.866*x1)} {f(.5*x1)})'
def box(x0,y0,w,d,h,c,z=0,extra=''):
    t,l,r=c; x1=x0+w; y1=y0+d
    s=f'<rect x="{x0}" y="{-(z+h)}" width="{w}" height="{h}" fill="{l}" transform="{LEFT(y1)}"/>'
    s+=f'<rect x="{y0}" y="{-(z+h)}" width="{d}" height="{h}" fill="{r}" transform="{RIGHT(x1)}"/>'
    s+=f'<rect x="{x0}" y="{y0}" width="{w}" height="{d}" fill="{t}" transform="{TOP(z+h)}"{extra}/>'
    return s
def scr(x,y,z=0): return ((x-y)*.866, (x+y)*.5-z)
PAL=('#ECC994','#D7A96B','#BC8D52')
BLD=('#6E95F0','#3E6FE2','#2B57C2')
TRK=('#FFFFFF','#EEF2FA','#D3DCEC')
CAB=('#4A80EE','#2F6FE4','#2152B8')
FK=('#F7C247','#E8A920','#C98B0E')
MAST=('#56607A','#3A4256','#2A3142')
out=[]
# ground
out.append(f'<rect x="0" y="0" width="960" height="760" rx="24" fill="#E6EDFB" transform="{TOP(0)}"/>')
out.append(f'<rect x="0" y="660" width="960" height="80" fill="#CBD6EB" transform="{TOP(0)}"/>')
for k in range(12):
    out.append(f'<rect x="{k*80+20}" y="698" width="40" height="4" fill="#FFFFFF" transform="{TOP(0)}"/>')
pads=[('ARRIVING',60,340,270,270,'#D8E5FF','#2F6FE4'),('STORED',360,340,240,270,'#D3EFE8','#167A73'),('LEAVING',630,340,270,270,'#FDE6D2','#B85F12')]
for name,x0,y0,w,d,fill,ink in pads:
    out.append(f'<rect x="{x0}" y="{y0}" width="{w}" height="{d}" rx="10" fill="{fill}" stroke="{ink}" stroke-width="2" stroke-dasharray="10 8" transform="{TOP(0)}"/>')
    out.append(f'<text x="{x0+16}" y="{y0+d-18}" fill="{ink}" font-size="22" font-weight="800" letter-spacing="3" transform="{TOP(0)}">{name}</text>')
items=[]
# trees (2d)
def tree(x,y,r=22):
    X,Y=scr(x,y); return (x+y-1,f'<rect x="{f(X-3)}" y="{f(Y-20)}" width="6" height="20" rx="2" fill="#7A6A55"/><circle cx="{f(X)}" cy="{f(Y-34)}" r="{r}" fill="#7CCB8E"/><circle cx="{f(X-6)}" cy="{f(Y-40)}" r="{r*0.45}" fill="#9BDCA9"/>')
for t in [(40,60),(60,230),(920,70),(930,250),(30,620)]: items.append(tree(*t))
# building
b=box(140,60,660,230,140,BLD)
y1=290
for dx in [200,350,500,650]:
    b+=f'<rect x="{dx}" y="-74" width="64" height="74" fill="#DCE6FB" transform="{LEFT(y1)}"/>'
    for k in range(1,6): b+=f'<rect x="{dx}" y="{-74+k*12}" width="64" height="1.5" fill="#B9C8EC" transform="{LEFT(y1)}"/>'
b+=f'<text x="180" y="-100" fill="#FFFFFF" font-size="26" font-weight="800" letter-spacing="4" transform="{LEFT(y1)}">SIMPLE WMS</text>'
# roof ridges
for k in range(1,8): b+=f'<rect x="{140+k*82}" y="60" width="3" height="230" fill="#5E86E6" transform="{TOP(140)}"/>'
items.append((200,b))
def pal(x,y,z=0,sel=False):
    extra=' stroke="#1F5FE0" stroke-width="3"' if sel else ''
    s=box(x,y,44,44,8,('#C99A5E','#B4844A','#9A6E3A'),z)
    s+=box(x+2,y+2,40,40,26,PAL,z+8,extra)
    return (x+y+ (0.5 if z else 0), s)
arr=[(90,375),(150,375),(90,435),(215,450),(150,505),(100,520)]
for p in arr: items.append(pal(*p))
items.append(pal(90,375,34))
sto=[(390,370),(450,370),(510,370),(390,440),(450,440),(510,440),(390,520)]
for p in sto: items.append(pal(*p))
for p in [(390,370),(450,370),(510,370),(390,440)]: items.append(pal(p[0],p[1],34))
items.append(pal(470,520))
for p in [(670,380),(730,380),(670,445),(790,470)]: items.append(pal(*p))
items.append(pal(670,380,34))
def forklift(x,y):
    s=box(x,y,40,30,24,FK)+box(x+4,y+4,20,22,16,('#3A4256','#2A3142','#20263A'),24)
    s+=box(x+40,y+2,6,26,60,MAST)
    s+=box(x+46,y+4,22,6,4,MAST)+box(x+46,y+20,22,6,4,MAST)
    return (x+y,s)
def truck(x,y,label):
    s=box(x,y,170,56,78,TRK,10)+box(x+170,y+4,46,48,60,CAB,10)
    s+=box(x+200,y+8,14,40,20,('#BFD3FA','#9DB8F0','#86A3E0'),46)
    for wx in [x+30,x+70,x+190]:
        s+=f'<circle cx="{wx}" cy="-8" r="11" fill="#2A3142" transform="{LEFT(y+56)}"/>'
    s+=f'<text x="{x+22}" y="-46" fill="#2F6FE4" font-size="18" font-weight="800" letter-spacing="2" transform="{LEFT(y+56)}">{label}</text>'
    return (x+y,s)
items.sort(key=lambda t:t[0])
base = out + [s for _,s in items]
layers = {
    "FORKLIFT_A": forklift(250,540)[1],
    "FORKLIFT_B": forklift(560,580)[1],
    "TRUCK_IN": truck(50,668,'DELIVERY')[1],
    "TRUCK_OUT": truck(660,668,'OUTBOUND')[1],
}
import json, os
here = os.path.dirname(os.path.abspath(__file__))
dest = os.path.join(here, "..", "src", "ui", "map", "warehouseLayers.ts")
with open(dest, "w") as fh:
    fh.write("/* Generated by scripts/warehouse_layers.py. Do not edit by hand. */\n")
    fh.write("/** Everything that stays still: ground, zones, building, pallets, trees. */\n")
    fh.write("export const BASE = " + json.dumps("".join(base)) + ";\n")
    for k, v in layers.items():
        fh.write("export const " + k + " = " + json.dumps(v) + ";\n")
